name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Bash Commands  # New step for Bash commands
      run: |
        echo "Running bash commands"
        echo "Current directory: $(pwd)"
        ls -la

    - name: Run Python script
      run: python monitor_script.py  # Update this path if needed
