name: Worm Detection CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: List repository contents
      run: |
        echo "Contents of the root directory:"
        ls -la

    - name: Run monitor script
      run: |
        echo "Running monitor_script.py..."
        python monitor_script.py

    - name: Run YARA Scan
      run: |
        echo "Running YARA scan..."
        bash scripts/run_yara.sh

    - name: Additional Bash Commands
      run: |
        echo "Running additional Bash commands..."
        # Add your custom Bash commands here
        # Example: ./scripts/your_custom_script.sh
        # Example: echo "Custom command executed"
